name: Daily Version Check and Notification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest

    env:
      PROD_URL: "https://shinny.org/us/ny/hrsn/index.html"
      QA_URL: "https://test.shinny.org"
      PROD_VERSION_FILE: "versions/prod_version.txt"
      QA_VERSION_FILE: "versions/qa_version.txt"
      HELP_EMAIL: "nidhin-unni@netspective.in"

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install tools
      run: sudo apt-get install -y jq grep

    - name: Fetch and parse PROD version
      id: fetch_prod
      run: |
        echo "Fetching PROD version..."
        curl -s "$PROD_URL" -o prod_response.html
        PROD_VERSION=$(grep -oP 'build\s*\(v\K[^\)]+' prod_response.html || echo "unknown")
        echo "Fetched PROD version: $PROD_VERSION"
        echo "PROD_VERSION=$PROD_VERSION" >> $GITHUB_ENV

    - name: Fetch and parse QA version
      id: fetch_qa
      run: |
        echo "Fetching QA version..."
        curl -s "$QA_URL" -o qa_response.html
        QA_VERSION=$(grep -oP 'build\s*\(v\K[^\)]+' qa_response.html || echo "unknown")
        echo "Fetched QA version: $QA_VERSION"
        echo "QA_VERSION=$QA_VERSION" >> $GITHUB_ENV

    - name: Compare versions
      id: compare_versions
      run: |
        echo "Comparing versions..."
        PROD_UPDATED=false
        QA_UPDATED=false

        STORED_PROD_VERSION=$(cat $PROD_VERSION_FILE)
        if [[ "$PROD_VERSION" != "$STORED_PROD_VERSION" ]]; then
          echo "PROD version updated!"
          echo "PROD_UPDATED=true" >> $GITHUB_ENV
        fi

        STORED_QA_VERSION=$(cat $QA_VERSION_FILE)
        if [[ "$QA_VERSION" != "$STORED_QA_VERSION" ]]; then
          echo "QA version updated!"
          echo "QA_UPDATED=true" >> $GITHUB_ENV
        fi

    - name: Create GitHub Issue for PROD
      if: env.PROD_UPDATED == 'true'
      run: |
        ISSUE_TITLE="PROD - NYeC Published IG Updated to ${PROD_VERSION}"
        ISSUE_BODY="A new version (${PROD_VERSION}) has been published for PROD. \n\n Please review and create a release following internal processes."
        API_JSON=$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" '{title: $title, body: $body}')
        RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "$API_JSON" "https://api.github.com/repos/${{ github.repository }}/issues")
        PROD_ISSUE_URL=$(echo "$RESPONSE" | jq -r '.html_url')
        echo "PROD_ISSUE_URL=$PROD_ISSUE_URL" >> $GITHUB_ENV

    - name: Create GitHub Issue for QA
      if: env.QA_UPDATED == 'true'
      run: |
        ISSUE_TITLE="QA - NYeC Published IG Updated to ${QA_VERSION}"
        ISSUE_BODY="A new version (${QA_VERSION}) has been published for QA. \n\n Please review and create a release following internal processes."
        API_JSON=$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" '{title: $title, body: $body}')
        RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "$API_JSON" "https://api.github.com/repos/${{ github.repository }}/issues")
        QA_ISSUE_URL=$(echo "$RESPONSE" | jq -r '.html_url')
        echo "QA_ISSUE_URL=$QA_ISSUE_URL" >> $GITHUB_ENV

    - name: Send email for PROD update
      if: env.PROD_UPDATED == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: email-smtp.us-east-1.amazonaws.com
        server_port: 587
        username: ${{ secrets.SES_SMTP_USERNAME }}
        password: ${{ secrets.SES_SMTP_PASSWORD }}
        subject: "PROD - NYeC Published IG Updated"
        to: ${{ env.HELP_EMAIL }}
        from: "Tech by Design Notification <no-reply@tx.techbd.org>"
        body: |
          A new PROD version has been detected and an issue has been created:
          Issue Link: ${{ env.PROD_ISSUE_URL }}
          Version: ${{ env.PROD_VERSION }}

    - name: Send email for QA update
      if: env.QA_UPDATED == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: email-smtp.us-east-1.amazonaws.com
        server_port: 587
        username: ${{ secrets.SES_SMTP_USERNAME }}
        password: ${{ secrets.SES_SMTP_PASSWORD }}
        subject: "QA - NYeC Published IG Updated"
        to: ${{ env.HELP_EMAIL }}
        from: "Tech by Design Notification <no-reply@tx.techbd.org>"
        body: |
          A new QA version has been detected and an issue has been created:
          Issue Link: ${{ env.QA_ISSUE_URL }}
          Version: ${{ env.QA_VERSION }}

    - name: Update stored version numbers
      run: |
        if [[ "$PROD_UPDATED" == "true" ]]; then
          echo "$PROD_VERSION" > $PROD_VERSION_FILE
        fi
        if [[ "$QA_UPDATED" == "true" ]]; then
          echo "$QA_VERSION" > $QA_VERSION_FILE
        fi
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add $PROD_VERSION_FILE $QA_VERSION_FILE
        git commit -m "Update stored versions"
        git push

    - name: Handle errors
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: email-smtp.us-east-1.amazonaws.com
        server_port: 587
        username: ${{ secrets.SES_SMTP_USERNAME }}
        password: ${{ secrets.SES_SMTP_PASSWORD }}
        subject: "[Alert] Failure in NYeC Published IG Check Workflow"
        to: ${{ env.HELP_EMAIL }}
        from: "Tech by Design Alert <no-reply@tx.techbd.org>"
        body: |
          The daily version check workflow has failed. 
          Please review the GitHub Actions logs for details.
