name: FHIR Bundle SmokeTest
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven

    - name: Download and setup JMeter
      run: |
        curl -O https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        sudo mv apache-jmeter-5.6.3 ./test-automation/

    - name: Run FHIR Bundle SmokeTest - Devl
      run: |
       mkdir -p ./test-automation/JmeterDevlReport/bundletest
       ./test-automation/apache-jmeter-5.6.3/bin/jmeter -n -t "./test-automation/FHIR-Bundle-SmokeTest-Devl/Bundle.jmx" -l "./test-automation/JmeterDevlResult/bundletest2.jtl"
       ./test-automation/apache-jmeter-5.6.3/bin/jmeter -g "./test-automation/JmeterDevlResult/bundletest2.jtl" -o "./test-automation/JmeterDevlReport/bundletest2"

    - name: Run FHIR Bundle SmokeTest - Stage
      run: |
        mkdir -p ./test-automation/JmeterStageReport/bundletest
        ./test-automation/apache-jmeter-5.6.3/bin/jmeter -n -t "./test-automation/FHIR-Bundle-SmokeTest-Stage/Bundle.jmx" -l "./test-automation/JmeterStageResult/bundletest.jtl"
        ./test-automation/apache-jmeter-5.6.3/bin/jmeter -g "./test-automation/JmeterStageResult/bundletest.jtl" -o "./test-automation/JmeterStageReport/bundletest"

   # - name: Run FHIR Bundle SmokeTest - QA
   #   run: |
   #     /home/ubuntu/apache-jmeter-5.6.3/bin/jmeter -n -t "/home/ubuntu/apache-jmeter-5.6.3/FHIR-Bundle-SmokeTest-PHI-QA/Bundle.jmx" -l "/home/ubuntu/JmeterPHIQAResult/bundletest.jtl"
   #     /home/ubuntu/apache-jmeter-5.6.3/bin/jmeter -g "/home/ubuntu/JmeterPHIQAResult/bundletest.jtl" -o "/home/ubuntu/JmeterPHIQAReport/bundletest"

    - name: Archive JMeter Reports into ZIP files
      run: |
        sudo apt-get install -y zip
        zip -r ./JmeterDevlReport.zip ./test-automation/JmeterDevlReport/bundletest2
        zip -r ./JmeterStageReport.zip ./test-automation/JmeterStageReport/bundletest
    #    zip -r ./JmeterPHIQAReport.zip /home/ubuntu/JmeterPHIQAReport/bundletest

    - name: Send email with JMeter reports
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: email-smtp.us-east-1.amazonaws.com
        server_port: 587
        username: ${{ secrets.SES_SMTP_USERNAME }}
        password: ${{ secrets.SES_SMTP_PASSWORD }}
        subject: "TechBD FHIR Bundle SmokeTest"
        body: |
            Hello Team,
            
            This is an automated notification for the FHIR Bundle SmokeTest results generated every hour.  

            **Test Summary (Hourly Run):**
            - **Development Report**: Attached
            - **Stage Report**: Attached
            - **QA Report**: Attached

            Please find the attached reports for detailed results of the tests executed during the last hour.

            Regards,  
            Tech by Design Automation Team  

        content_type: "text/plain"
        from: "Tech by Design FHIR SmokeTest Result <no-reply@tx.techbd.org>"
        to: nidhin-unni@netspective.in, rinshad-asharaf@netspective.in
        attachments: |
          ./JmeterDevlReport.zip        
          ./JmeterStageReport.zip
    #      ./JmeterPHIQAReport.zip
